### ISSUE TITLE
hubot-fb on heroku

### ISSUE THREAD

**Issue by daniftodi** [chen-ye/hubot-fb#1]
Hi,

I'm using Hubot on Heroku with Slack. Now I try to use with facebook. Please explain me how to get setup webhooks on facebook so hubot-fb can listen for new messages ?

**Comment by chen-ye** [comment]
Hi!  

The readme should get you started: https://github.com/chen-ye/hubot-fb#installation

Here are more detailed setup instructions:

You first want to install and configure hubot-fb on the hubot end by running `npm install -save hubot-fb` in your Hubot's root.  

Then, set hubot-fb as your adapter by launching with bin/hubot -a fb. (Edit your Procfile to do the same on Heroku.)

Then, create a Facebook page [here](https://www.facebook.com/pages/create/)

After your page is set up, create an app [here](https://developers.facebook.com/quickstarts/?platform=web).  After you create an app ID and enter you email, click 
![image](https://cloud.githubusercontent.com/assets/1904031/14604137/3cd8d8ee-0572-11e6-9072-724c0f73c21e.png)

Once your app is set up, go to your app dashboard and click "Messenger" on the sidebar.  It should look something like this:

![image](https://cloud.githubusercontent.com/assets/1904031/14604183/71017e6e-0572-11e6-888e-1cea71ca34e0.png)

Now, under "Token Generation", select a page, and copy the page access token that is generated:
![image](https://cloud.githubusercontent.com/assets/1904031/14604243/da3d106e-0572-11e6-822e-ac15322bf94b.png)

Set this token as your `FB_PAGE_TOKEN`environment variable.

This will allow your bot to send as your page.

**IMPORTANT** You then need to run 
`curl -ik -X POST "https://graph.facebook.com/v2.6/me/subscribed_apps?access_token=[FB_PAGE_TOKEN]"`.  This tells Facebook to forward page messages to your app.  

Then pick any alphanumeric string for your `FB_VERIFY_TOKEN`.

Launch your hubot instance now.

In your app dashboard, under the webhooks section, click setup webhooks:
![image](https://cloud.githubusercontent.com/assets/1904031/14604352/68dbc5c2-0573-11e6-9891-cd79b020b642.png).  

You should see a dialog like this: 
![image](https://cloud.githubusercontent.com/assets/1904031/14604367/859b3e68-0573-11e6-8d6e-96e41663786f.png)

Under "Callback URL", input `[your hubot domain]/hubot/` (for ex, `test-bot.herokuapp.com/hubot/`) (you can customize the route by setting `FB_ROUTE_URL`).  

Under "Verify Token", input the token you set for `FB_VERIFY_TOKEN`.

Check all the boxes under "Subscription Fields" and click "Verify and Save".  This should create webhooks which allow your page to receive Page messages.  

That should be everything you need to get started developing.  You'll then, ofc, need to pass FB App Review.  

Let me know if you have any other questions!

**Comment by chen-ye** [comment]
added more detailed install instructions to documentation https://github.com/chen-ye/hubot-fb/commit/cf07acd4aa3dc0b33e2cf667a4f8576fc621c08a

**Comment by kengz** [comment]
fyi @daniftodi PR #4 does this automatically for you.
