### ISSUE TITLE
set webhook programmatically

### ISSUE THREAD

**Issue by kengz** [chen-ye/hubot-fb#3]
Hey, do you know if Facebook has an API for setting webhook programmatically? (this bypass the manual usage of the web interface to do that). For example Telegram does this nicely on [their API](https://core.telegram.org/bots/api#setwebhook).

This would open up the use cases a lot. I'm automating `ngrok` that generates a webhook URL on the go, and use the API to set a new webhook with Telegram's API. Hopefully this can be done with facebook too.

Let me know what u think!

**Comment by kengz** [comment]
After some digging, the answer is yes: [subscriptions API](https://developers.facebook.com/docs/graph-api/reference/v2.6/app/subscriptions), [webhook ref](https://developers.facebook.com/docs/messenger-platform/webhook-reference). Would look into that first myself, but if you have a quicker way to build it into your adapter to read an environment variable, like how [hubot-telegram](https://github.com/lukefx/hubot-telegram) does it, it'd be great. Plus you are definitely more familiar with the FB API and your adapter than I am :)

I'm finishing the "omnipresence" feature of my bot, i.e. it'd be able to be deployed to Slack, Telegram, FB simultaneously (yes, still is one bot that you can talk to from anywhere). 

All the setups will be automated too, and so I need the programmatic setting of the FB webhook url. When that's done, people will be able to install and deploy a bot in only [3 lines of commands](http://kengz.me/aiva-doc/#setup-run)!

I must say this project of yours is awesome :) Appreciate the work you do. Imagine the possibilities it opens up as it gets refined and allows developers to write bots more easily.

**Comment by chen-ye** [comment]
Sweet!  I'll take a look at your project!  Thanks for reporting back what you found!

**Comment by kengz** [comment]
quick reference to save u more time: [telegram setwebhook example](https://github.com/lukefx/hubot-telegram/blob/master/src/telegram.coffee#L221), and my failed quick attempt:

```
function setupWebhook(page_id, verify_token, callback_url) {
  var formData = {
    access_token: access_token,
    callback_url: callback_url,
    verify_token: verify_token,
    object: 'page',
    fields: ['messaging_optins', 'messages', 'message_deliveries', 'messaging_postbacks'],

  }
  var options = {
    method: 'POST',
    json: true,
    baseUrl: 'https://graph.facebook.com',
    url: '/v2.6/'+page_id+'/subscriptions',
    formData: formData
  }
  request(options, function(err, res, body) {
    if (err) { throw err };
    console.log(res)
    console.log(body)
  })
}
```

was prolly hitting the wrong endpoints or not completing the needed pre-verifications.

I included `ngrok` in the project to automatically pass a redirected url of an exposed local port, so this can be put into environment variables before initializing the adapter (where you come in). Excited to hear about your progress on that!

**Comment by kengz** [comment]
YASSS I've just got it! Will refactor properly and paste it here tonight so you can merge it into this repo. Meanwhile going back to rock climbing :)

**Comment by chen-ye** [comment]
implemented with https://github.com/chen-ye/hubot-fb/pull/5

**Comment by titulus** [comment]
@kengz is it working now?
It was all ok few days ago, but today (28.03.2017) I getting error like:
`[Tue Mar 28 2017 09:36:00 GMT+0300 (+03)] INFO FB webhook set/updated: {"error":{"message":"Invalid OAuth access token signature.","type":"OAuthException","code":190,"fbtrace_id":"ARkneyAPmJG"}}`

**Comment by kengz** [comment]
It should still works; the oauth token seems to be some error in the the secrets you provided when sending the hook. recheck and make sure the token used is right?
